framework:
    messenger:
        failure_transport: failed

        transports:
            # RabbitMQ Transport for asynchronous messaging
            rabbitmq:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: orders_exchange # Custom exchange name
                        type: direct
                    queues:
                        orders_queue: ~ # Custom queue name

            # Failed transport for storing failed messages
            failed: "doctrine://default?queue_name=failed"

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Route OrderMessage to RabbitMQ transport
            App\Message\OrderMessage: rabbitmq
